export const equipos = [
    { id: 1, name: 'argentinos juniors', img: '/images/equipos/argentinos.png', nameForAPI: 'Argentinos JRS' },
    { id: 2, name: 'atlético tucumán', img: '/images/equipos/atleticotucuman.png', nameForAPI: 'Atletico Tucuman' },
    { id: 3, name: 'banfield', img: '/images/equipos/banfield.png', nameForAPI: 'Banfield' },
    { id: 4, name: 'barracas central', img: '/images/equipos/barracas.png', nameForAPI: 'Barracas Central' },
    { id: 5, name: 'belgrano', img: '/images/equipos/belgrano.png', nameForAPI: 'Belgrano Cordoba' },
    { id: 6, name: 'boca juniors', img: '/images/equipos/boca.png', nameForAPI: 'Boca Juniors' },
    { id: 7, name: 'central córdoba', img: '/images/equipos/centralcordoba.png', nameForAPI: 'Central Cordoba de Santiago' },
    { id: 8, name: 'defensa y justicia', img: '/images/equipos/defensa.png', nameForAPI: 'Defensa Y Justicia' },
    { id: 9, name: 'estudiantes L.P.', img: '/images/equipos/estudiantes.png', nameForAPI: 'Estudiantes L.P.' },
    { id: 10, name: 'gimnasia L.P.', img: '/images/equipos/gimnasia.png', nameForAPI: 'Gimnasia L.P.' },
    { id: 11, name: 'godoy cruz', img: '/images/equipos/godoycruz.png', nameForAPI: 'Godoy Cruz' },
    { id: 12, name: 'huracán', img: '/images/equipos/huracan.png', nameForAPI: 'Huracan' },
    { id: 13, name: 'ind. rivadaria', img: '/images/equipos/independienteriv.png', nameForAPI: 'Independiente Rivadavia' },
    { id: 14, name: 'independiente', img: '/images/equipos/independiente.png', nameForAPI: 'Independiente' },
    { id: 15, name: 'instituto', img: '/images/equipos/instituto.png', nameForAPI: 'Instituto Cordoba' },
    { id: 16, name: 'lanús', img: '/images/equipos/lanus.png', nameForAPI: 'Lanus' },
    { id: 17, name: "newell's", img: '/images/equipos/newells.png', nameForAPI: 'Newells Old Boys' },
    { id: 18, name: 'platense', img: '/images/equipos/platense.png', nameForAPI: 'Platense' },
    { id: 19, name: 'racing club', img: '/images/equipos/racing.png', nameForAPI: 'Racing Club' },
    { id: 20, name: 'riestra', img: '/images/equipos/riestra.png', nameForAPI: 'Deportivo Riestra' },
    { id: 21, name: 'river plate', img: '/images/equipos/river.png', nameForAPI: 'River Plate' },
    { id: 22, name: 'rosario central', img: '/images/equipos/rosariocentral.png', nameForAPI: 'Rosario Central' },
    { id: 23, name: 'san lorenzo', img: '/images/equipos/sanlorenzo.png', nameForAPI: 'San Lorenzo' },
    { id: 24, name: 'sarmiento', img: '/images/equipos/sarmiento.png', nameForAPI: 'Sarmiento Junin' },
    { id: 25, name: 'talleres', img: '/images/equipos/talleres.png', nameForAPI: 'Talleres Cordoba' },
    { id: 26, name: 'tigre', img: '/images/equipos/tigre.png', nameForAPI: 'Tigre' },
    { id: 27, name: 'unión', img: '/images/equipos/union.png', nameForAPI: 'Union Santa Fe' },
    { id: 28, name: 'vélez', img: '/images/equipos/velez.png', nameForAPI: 'Velez Sarsfield' },
]